import React, { useState } from 'react';
import { AirGapNetworkMonitor } from './components/AirGapNetworkMonitor';
import { ModelRouterHUD } from './components/ModelRouterHUD';
import { AgentExecutionTree } from './components/AgentExecutionTree';
import { DeliverableExportPanel } from './components/DeliverableExportPanel';
import type {
  AgentExecutionState,
  AgentRoute,
  DeliverableFile
} from './types/workbench';

import {
  Play,
  FileUp,
  BookOpen,
  Sparkles,
  RotateCcw,
  FileCheck2,
  Code2,
  FileSpreadsheet,
  Eye,
  Calculator
} from 'lucide-react';


const PRESET_TASKS = [
  {
    title: 'Code Sandbox Task',
    icon: Code2,
    route: 'coding' as AgentRoute,
    prompt:
      'Write a Python function to calculate ASME B31.3 internal design pressure allowance for seamless carbon steel pipe.'
  },
  {
    title: 'Document & Approval Note',
    icon: FileSpreadsheet,
    route: 'document' as AgentRoute,
    prompt:
      'Summarize the crude distillation unit inspection report and draft a formal PSU approval note for scheduled turnaround maintenance.'
  },
  {
    title: 'Engineering Calculation',
    icon: Calculator,
    route: 'calculation' as AgentRoute,
    prompt:
      'Calculate the remaining safe operational life of a pipeline with 3.4mm current thickness, 0.15mm/year corrosion rate, and 2.0mm retirement thickness.'
  },
  {
    title: 'P&ID Drawing Analysis',
    icon: Eye,
    route: 'vision' as AgentRoute,
    prompt:
      'Analyze scanned P&ID drawing sheet 4 for bypass line valves and flag any unverified pressure relief connections.'
  }
];


export const App: React.FC = () => {

  const [prompt, setPrompt] =
    useState(PRESET_TASKS[0].prompt);

  const [selectedPreset, setSelectedPreset] =
    useState<number>(0);

  const [isRunning, setIsRunning] =
    useState(false);

  const [uploadedFile, setUploadedFile] =
    useState<string | null>(
      'Refinery_Unit_4_Inspection_Scan.pdf'
    );


  const [executionState, setExecutionState] =
    useState<AgentExecutionState>({
      question: PRESET_TASKS[0].prompt,
      route: 'coding',

      supervisor_reason:
        'The request is related to software development and engineering calculation script execution.',

      plan: [
        '1. Parse ASME B31.3 equation parameters: pressure (P), allowable stress (S), joint quality factor (E), diameter (D), thickness (t).',
        '2. Implement formula: P = (2 * S * E * t) / (D - 2 * y * t) in sandboxed Python environment.',
        '3. Run unit tests with standard Grade B carbon steel parameters.',
        '4. Verify calculations and format deliverables.'
      ],

      current_agent: 'coding_agent',

      agent_result: `def asme_b31_3_internal_pressure(S, E, t, D, y=0.4, c=0.0):
    """
    Calculates ASME B31.3 internal design gage pressure for straight pipe.
    S: Basic allowable stress (psi)
    E: Quality factor (e.g. 1.0 for seamless)
    t: Pressure design thickness (inches)
    D: Outside diameter of pipe (inches)
    y: Coefficient from Table 304.1.1
    c: Sum of mechanical allowances plus corrosion allowance
    """

    t_net = t - c

    if t_net <= 0:
        raise ValueError("Net wall thickness must be positive.")

    P = (2 * S * E * t_net) / (D - 2 * y * t_net)

    return round(P, 2)

# Sample Verification Execution:
# S = 20,000 psi, E = 1.0, t = 0.375", D = 6.625"
p_max = asme_b31_3_internal_pressure(
    20000,
    1.0,
    0.375,
    6.625
)

print(f"Maximum Allowable Working Pressure: {p_max} psig")`,

      tool_results: [
        'Sandbox Execution Result: Returncode 0 | MAWP: 2371.55 psig'
      ],

      observations: [
        'Coding Agent completed the requested task in isolated sandbox.'
      ],

      verification:
        'STATUS: PASS\nAll parameters comply with ASME Section VIII / B31.3 Table 304.1.1 rules. Code runs cleanly without warnings.',

      verification_status: true,

      retry_count: 0,

      final_answer:
        `### ASME B31.3 Pipe Pressure Calculation Module Verified

The Python implementation correctly models internal design gage pressure according to Paragraph 304.1.2:

- Formula: P = (2SEt) / (D - 2yt)
- Sandbox Result: Tested on 6" Schedule 40 carbon steel pipe yielding 2371.55 psig MAWP.
- Sovereign Status: Code executed and verified entirely inside local environment. No data transmitted externally.`,

      elapsed_seconds: 1.62
    });


  const [deliverables, setDeliverables] =
    useState<DeliverableFile[]>([
      {
        id: 'deliv-1',
        name: 'asme_b31_3_pressure_calc.py',
        format: 'py',
        size: '1.8 KB',
        agentSource: 'Qwen-2.5-Coder-7B',

        content: `# ASME B31.3 Pressure Calculation Script
# Generated by Sovereign On-Premise AI Workbench

def asme_b31_3_internal_pressure(S, E, t, D, y=0.4, c=0.0):
    t_net = t - c
    P = (2 * S * E * t_net) / (D - 2 * y * t_net)
    return round(P, 2)

if __name__ == "__main__":
    print(
        "MAWP:",
        asme_b31_3_internal_pressure(
            20000,
            1.0,
            0.375,
            6.625
        ),
        "psig"
    )
`
      },

      {
        id: 'deliv-2',
        name: 'PSU_Equipment_Integrity_Approval_Note.docx',
        format: 'docx',
        size: '24.5 KB',
        agentSource: 'DeepSeek-R1-14B',

        content: `CONFIDENTIAL - FOR INTERNAL PSU REVIEW ONLY
APPROVAL NOTE: PIPELINE INTEGRITY ASSESSMENT & REPLACEMENT
Date: September 16, 2026
Department: Mechanical Integrity & Asset Reliability
Subject: Approval for Valve V-104 Replacement and Shutdown Scheduling

1. Background: Routine ultrasonic thickness testing revealed anomalous wall thinning.
2. Calculations: Remaining operational life evaluated at 142 days using ASME safety factors.
3. Recommendation: Procure replacement spool piece under scheduled turnaround.`
      }
    ]);


  /*
   * REAL BACKEND CONNECTION
   *
   * Frontend
   *    ↓
   * Java Spring Boot :8080
   *    ↓
   * /api/agent/run
   *    ↓
   * Python FastAPI :8000
   *    ↓
   * LangGraph + Groq
   */

  const handleExecute = async () => {

    if (!prompt.trim()) {
      return;
    }

    setIsRunning(true);

    const startTime = performance.now();

    try {

      const response = await fetch(
        'http://localhost:8080/api/agent/run',
        {
          method: 'POST',

          headers: {
            'Content-Type': 'application/json'
          },

          body: JSON.stringify({
            question: prompt,

            context: uploadedFile
              ? `Attached document: ${uploadedFile}`
              : ''
          })
        }
      );


      if (!response.ok) {

        throw new Error(
          `Java backend returned HTTP ${response.status}`
        );
      }


      const data = await response.json();


      const plan: string[] =
        Array.isArray(data.plan)
          ? data.plan.map(
              (item: unknown) => String(item)
            )
          : [];


      const verification: string =
        data.verification ?? '';


      const verificationStatus: boolean =
        verification.includes('STATUS: PASS');


      const elapsedSeconds =
        (performance.now() - startTime) / 1000;


      setExecutionState({

        question: prompt,

        route:
          data.route ?? 'general',

        supervisor_reason:
          data.supervisorReason ?? '',

        plan,

        current_agent:
          data.currentAgent ?? 'general_agent',

        agent_result:
          data.finalAnswer ?? '',

        tool_results: [],

        observations: [],

        verification,

        verification_status:
          verificationStatus,

        retry_count: 0,

        final_answer:
          data.finalAnswer ??
          'The agent did not return a final answer.',

        elapsed_seconds:
          Number(elapsedSeconds.toFixed(2))
      });


      /*
       * Add a simple real deliverable for
       * coding/document routes so the existing
       * deliverable panel can display output.
       */

      if (data.route === 'coding') {

        setDeliverables(prev => [
          {
            id: `deliv-${Date.now()}`,

            name: 'agent_generated_result.txt',

            format: 'txt',

            size: `${String(data.finalAnswer ?? '').length} bytes`,

            agentSource:
              data.currentAgent ?? 'Agent',

            content:
              data.finalAnswer ??
              'No final answer returned.'
          },

          ...prev
        ]);
      }


      if (data.route === 'document') {

        setDeliverables(prev => [
          {
            id: `deliv-${Date.now()}`,

            name: 'agent_document_result.txt',

            format: 'txt',

            size: `${String(data.finalAnswer ?? '').length} bytes`,

            agentSource:
              data.currentAgent ?? 'Agent',

            content:
              data.finalAnswer ??
              'No final answer returned.'
          },

          ...prev
        ]);
      }


    } catch (error) {

      console.error(
        'Failed to connect to Java backend:',
        error
      );


      setExecutionState({

        question: prompt,

        route: 'general',

        supervisor_reason:
          'Unable to connect to the Java Spring Boot backend.',

        plan: [],

        current_agent:
          'backend_unavailable',

        agent_result:
          'The Java Spring Boot backend could not be reached.',

        tool_results: [],

        observations: [],

        verification:
          'STATUS: FAILED\nBackend connection failed.',

        verification_status:
          false,

        retry_count: 0,

        final_answer:
          'Unable to connect to the Java Spring Boot backend. Make sure Spring Boot is running on port 8080.',

        elapsed_seconds: 0
      });

    } finally {

      setIsRunning(false);

    }
  };


  const handleSelectPreset =
    (idx: number) => {

      setSelectedPreset(idx);

      setPrompt(
        PRESET_TASKS[idx].prompt
      );
    };


  return (

    <div className="h-screen w-screen flex flex-col bg-[#070a0f] text-slate-100 overflow-hidden font-sans">

      {/* 1. Top Air-Gap Verification Monitor */}

      <AirGapNetworkMonitor />


      {/* 2. Hackathon Scenario Preset Bar */}

      <div className="bg-[#0b1019] border-b border-[#1e293b] px-4 py-2 flex items-center justify-between">

        <div className="flex items-center space-x-2">

          <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
            Industrial Task Scenarios:
          </span>


          <div className="flex space-x-2">

            {PRESET_TASKS.map(
              (preset, idx) => {

                const Icon =
                  preset.icon;

                const isSelected =
                  selectedPreset === idx;

                return (

                  <button
                    key={preset.title}
                    onClick={() =>
                      handleSelectPreset(idx)
                    }
                    className={`flex items-center space-x-1.5 px-2.5 py-1 rounded text-xs font-medium transition-all ${
                      isSelected
                        ? 'bg-sky-950 text-sky-300 border border-sky-600 shadow-sm'
                        : 'bg-[#0f1724] text-slate-400 border border-[#1e293b] hover:text-slate-200'
                    }`}
                  >

                    <Icon className="w-3.5 h-3.5" />

                    <span>
                      {preset.title}
                    </span>

                  </button>
                );
              }
            )}

          </div>

        </div>


        <div className="text-[11px] text-emerald-400 bg-emerald-950/40 px-2.5 py-0.5 rounded border border-emerald-800 flex items-center space-x-1">

          <FileCheck2 className="w-3.5 h-3.5" />

          <span>
            Local SOP Vault Active
            (ASME B31.3, PSU Ref-204)
          </span>

        </div>

      </div>


      {/* 3. Main 3-Column Workbench */}

      <div className="flex-1 grid grid-cols-12 gap-3 p-3 overflow-hidden">


        {/* LEFT COLUMN */}

        <div className="col-span-4 flex flex-col space-y-3 h-full overflow-hidden">

          <div className="bg-[#0f1724] border border-[#1e293b] rounded-lg p-3.5 flex flex-col flex-1 overflow-hidden">

            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200 mb-2 flex items-center justify-between">

              <span>
                Task & Industrial Input
              </span>

              <span className="text-[10px] text-sky-400 font-normal">
                Air-Gapped Ingestion
              </span>

            </h3>


            {/* File Area */}

            <div
              onClick={() =>
                setUploadedFile(
                  prev =>
                    prev
                      ? null
                      : 'Refinery_Unit_4_Inspection_Scan.pdf'
                )
              }

              className="border border-dashed border-[#1e293b] hover:border-sky-500/80 rounded-md p-2.5 text-center cursor-pointer transition-colors bg-[#0a0f18] mb-3"

              title="Click to toggle sample scanned drawing"
            >

              <FileUp className="w-5 h-5 mx-auto text-slate-400 mb-1" />


              <div className="text-xs font-medium text-slate-300">

                {uploadedFile ? (

                  <span className="text-sky-400">
                    {uploadedFile}
                  </span>

                ) : (

                  'Attach Scanned PDF / P&ID Drawing'

                )}

              </div>


              <div className="text-[10px] text-slate-500">

                Processed locally via on-device Vision weights

              </div>

            </div>


            {/* Prompt */}

            <div className="flex-1 flex flex-col">

              <label className="text-[11px] font-semibold text-slate-400 mb-1">

                Instruction / Objective

              </label>


              <textarea
                value={prompt}
                onChange={e =>
                  setPrompt(e.target.value)
                }

                placeholder="Enter engineering problem, calculation, or approval note request..."

                className="w-full flex-1 bg-[#090d14] border border-[#1e293b] focus:border-sky-500 rounded p-2.5 text-xs text-slate-200 focus:outline-none resize-none font-sans leading-relaxed"
              />

            </div>


            {/* Execute Button */}

            <button
              onClick={handleExecute}
              disabled={isRunning}

              className={`mt-3 py-2 px-4 rounded text-xs font-semibold flex items-center justify-center space-x-2 transition-all shadow ${
                isRunning
                  ? 'bg-slate-800 text-slate-500 cursor-not-allowed'
                  : 'bg-sky-600 hover:bg-sky-500 text-white shadow-sky-950'
              }`}
            >

              {isRunning ? (

                <>

                  <RotateCcw className="w-3.5 h-3.5 animate-spin" />

                  <span>
                    Iterating in LangGraph Sandbox...
                  </span>

                </>

              ) : (

                <>

                  <Play className="w-3.5 h-3.5 fill-current" />

                  <span>
                    Execute Sovereign Agent Pipeline
                  </span>

                </>

              )}

            </button>

          </div>


          {/* Knowledge Vault */}

          <div className="bg-[#0f1724] border border-[#1e293b] rounded-lg p-3">

            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300 mb-2 flex items-center space-x-1.5">

              <BookOpen className="w-3.5 h-3.5 text-amber-400" />

              <span>
                Grounding Knowledge Vault
              </span>

            </h4>


            <div className="space-y-1.5 text-[11px]">

              <div className="bg-[#0a0f18] p-2 rounded border border-[#1e293b]/70">

                <div className="font-semibold text-slate-300">
                  ASME B31.3 - Chapter II
                </div>

                <div className="text-[10px] text-slate-500">
                  Piping Design Equations & Allowable Stress Tables.
                </div>

              </div>


              <div className="bg-[#0a0f18] p-2 rounded border border-[#1e293b]/70">

                <div className="font-semibold text-slate-300">
                  PSU Standard SOP-MECH-204
                </div>

                <div className="text-[10px] text-slate-500">
                  Corrosion limits & Board Approval Note formats.
                </div>

              </div>

            </div>

          </div>

        </div>


        {/* CENTER COLUMN */}

        <div className="col-span-5 flex flex-col space-y-3 h-full overflow-hidden">

          <ModelRouterHUD
            currentAgent={
              executionState.current_agent
            }

            activeRoute={
              executionState.route
            }

            supervisorReason={
              executionState.supervisor_reason
            }
          />


          <div className="flex-1 overflow-hidden">

            <AgentExecutionTree
              state={executionState}
              isRunning={isRunning}
            />

          </div>

        </div>


        {/* RIGHT COLUMN */}

        <div className="col-span-3 flex flex-col space-y-3 h-full overflow-hidden">

          <DeliverableExportPanel
            deliverables={deliverables}
          />


          <div className="bg-[#0f1724] border border-[#1e293b] rounded-lg p-3 flex-1 flex flex-col">

            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300 mb-2 flex items-center space-x-1.5">

              <Sparkles className="w-3.5 h-3.5 text-emerald-400" />

              <span>
                Air-Gap Verification Proof
              </span>

            </h4>


            <p className="text-[11px] text-slate-400 mb-3">

              This workbench operates under zero-trust defense specifications:

            </p>


            <div className="space-y-2 text-xs flex-1">

              <div className="bg-[#0a0f18] p-2.5 rounded border border-[#1e293b]">

                <div className="text-slate-400 text-[10px]">
                  INDEPENDENT AUDIT
                </div>

                <div className="font-mono text-emerald-400 font-semibold mt-0.5">
                  0 OUTBOUND BYTES
                </div>

                <div className="text-[10px] text-slate-500">
                  Wi-Fi/WAN calls rejected by loopback firewall rule.
                </div>

              </div>


              <div className="bg-[#0a0f18] p-2.5 rounded border border-[#1e293b]">

                <div className="text-slate-400 text-[10px]">
                  MULTIMODAL ON-DEVICE
                </div>

                <div className="font-mono text-sky-400 font-semibold mt-0.5">
                  LOCAL WEIGHTS ONLY
                </div>

                <div className="text-[10px] text-slate-500">
                  P&ID images never leave the host GPU memory.
                </div>

              </div>


              <div className="bg-[#0a0f18] p-2.5 rounded border border-[#1e293b]">

                <div className="text-slate-400 text-[10px]">
                  EVALUATOR ACTION
                </div>

                <div className="text-slate-300 text-[11px] mt-0.5">
                  Disconnect your network cable during demo to verify 100% offline availability.
                </div>

              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  );
};


export default App;